import '../../../models/questions/mcq.dart';

final List<MCQ> dummyMCQs = [
  MCQ(
    id: 'mcq_1',
    bankId: '202',
    question: 'What is the chemical formula for water?',
    variableIds: [],
    points: 5,
    options: ['H₂O', 'CO₂', 'O₂', 'H₂'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_2',
    bankId: '202',
    question: 'What is the pH value of a neutral solution?',
    variableIds: [],
    points: 5,
    options: ['0', '7', '14', '10'],
    answerIndex: 1,
  ),
  MCQ(
    id: 'mcq_3',
    bankId: '201',
    question: 'What is the first law of motion proposed by Newton?',
    variableIds: [],
    points: 5,
    options: ['Law of Inertia', 'Law of Acceleration', 'Law of Action-Reaction', 'Law of Gravitation'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_4',
    bankId: '201',
    question: 'What is the unit of force in the International System of Units (SI)?',
    variableIds: [],
    points: 5,
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_5',
    bankId: '203',
    question: 'What is the solution to the equation 2x + 3 = 7?',
    variableIds: [],
    points: 5,
    options: ['x = 1', 'x = 2', 'x = 3', 'x = 4'],
    answerIndex: 1,
  ),
  // The rest of the MCQs remain unchanged
  MCQ(
    id: 'mcq_6',
    bankId: '204',
    question: 'Which organelle is known as the powerhouse of the cell?',
    variableIds: [],
    points: 5,
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic Reticulum'],
    answerIndex: 1,
  ),
  MCQ(
    id: 'mcq_7',
    bankId: '204',
    question: 'What is the main function of the cell membrane?',
    variableIds: [],
    points: 5,
    options: ['Protein synthesis', 'Energy production', 'Regulating the movement of substances in and out of the cell', 'DNA replication'],
    answerIndex: 2,
  ),
  MCQ(
    id: 'mcq_8',
    bankId: '205',
    question: 'Who was the Prime Minister of the United Kingdom during most of World War II?',
    variableIds: [],
    points: 5,
    options: ['Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Anthony Eden'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_9',
    bankId: '205',
    question: 'Which event marked the beginning of World War II?',
    variableIds: [],
    points: 5,
    options: ['The invasion of Poland', 'The attack on Pearl Harbor', 'The Battle of Britain', 'The signing of the Treaty of Versailles'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_10',
    bankId: '201',
    question: 'What is the first law of motion proposed by Newton?',
    variableIds: [],
    points: 5,
    options: ['Law of Inertia', 'Law of Acceleration', 'Law of Action-Reaction', 'Law of Gravitation'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_11',
    bankId: '201',
    question: 'What is the unit of force in the International System of Units (SI)?',
    variableIds: [],
    points: 5,
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_12',
    bankId: '203',
    question: 'What is the solution to the equation 2x + 3 = 7?',
    variableIds: [],
    points: 5,
    options: ['x = 1', 'x = 2', 'x = 3', 'x = 4'],
    answerIndex: 1,
  ),
  MCQ(
    id: 'mcq_13',
    bankId: '203',
    question: 'What is the value of x in the equation x² - 4 = 0?',
    variableIds: [],
    points: 5,
    options: ['x = 2', 'x = -2', 'x = ±2', 'x = 0'],
    answerIndex: 2,
  ),
  MCQ(
    id: 'mcq_14',
    bankId: '204',
    question: 'What is the function of ribosomes in a cell?',
    variableIds: [],
    points: 5,
    options: ['Protein synthesis', 'Energy production', 'DNA replication', 'Cell division'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_15',
    bankId: '202',
    question: 'What is the chemical formula for water?',
    variableIds: [],
    points: 5,
    options: ['H₂O', 'CO₂', 'O₂', 'H₂'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_16',
    bankId: '202',
    question: 'What is the pH value of a neutral solution?',
    variableIds: [],
    points: 5,
    options: ['0', '7', '14', '10'],
    answerIndex: 1,
  ),
  MCQ(
    id: 'mcq_17',
    bankId: '205',
    question: 'Which country was the first to declare war in World War I?',
    variableIds: [],
    points: 5,
    options: ['Germany', 'Austria-Hungary', 'France', 'Russia'],
    answerIndex: 1,
  ),
  MCQ(
    id: 'mcq_18',
    bankId: '205',
    question: 'What was the main cause of the Russian Revolution of 1917?',
    variableIds: [],
    points: 5,
    options: ['Economic hardship', 'Political repression', 'Military defeat', 'All of the above'],
    answerIndex: 3,
  ),
  MCQ(
    id: 'mcq_19',
    bankId: '206',
    question: 'What is the Heisenberg Uncertainty Principle?',
    variableIds: [],
    points: 5,
    options: ['It is impossible to know both the position and momentum of a particle simultaneously', 'Energy is quantized', 'Light behaves as both a particle and a wave', 'Electrons orbit the nucleus in fixed paths'],
    answerIndex: 0,
  ),
  MCQ(
    id: 'mcq_20',
    bankId: '207',
    question: 'What is the speed of light in a vacuum?',
    variableIds: [],
    points: 5,
    options: ['3 x 10⁸ m/s', '3 x 10⁶ m/s', '3 x 10⁴ m/s', '3 x 10² m/s'],
    answerIndex: 0,
  ),
];