import '../../../models/questions/msq.dart';

final List<MSQ> dummyMSQs = [
  MSQ(
    id: 'msq_1',
    bankId: '201',
    question: 'Which of the following are Newton\'s Laws of Motion?',
    variableIds: [],
    points: 6,
    options: [
      'Law of Inertia',
      'F = ma',
      'For every action, there is an equal and opposite reaction',
      'Energy cannot be created or destroyed',
    ],
    answerIndices: [0, 1, 2],
  ),
  MSQ(
    id: 'msq_2',
    bankId: '202',
    question: 'Which of the following are types of chemical reactions?',
    variableIds: [],
    points: 6,
    options: [
      'Synthesis',
      'Decomposition',
      'Single replacement',
      'Double replacement',
    ],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_3',
    bankId: '203',
    question: 'Which of the following are algebraic expressions?',
    variableIds: [],
    points: 5,
    options: ['2x + 3', 'x² - 4', '3y + 2z', '5'],
    answerIndices: [0, 1, 2],
  ),
  MSQ(
    id: 'msq_4',
    bankId: '204',
    question: 'Which of the following are parts of a cell?',
    variableIds: [],
    points: 4,
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Chloroplast'],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_5',
    bankId: '205',
    question: 'Which of the following were major events in World War II?',
    variableIds: [],
    points: 6,
    options: [
      'Invasion of Poland',
      'Attack on Pearl Harbor',
      'D-Day',
      'Hiroshima and Nagasaki bombings',
    ],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_6',
    bankId: '201',
    question: 'Which of the following are fundamental forces in physics?',
    variableIds: [],
    points: 5,
    options: [
      'Gravitational force',
      'Electromagnetic force',
      'Strong nuclear force',
      'Weak nuclear force',
    ],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_7',
    bankId: '202',
    question: 'Which of the following are states of matter?',
    variableIds: [],
    points: 4,
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_8',
    bankId: '203',
    question: 'Which of the following are prime numbers?',
    variableIds: [],
    points: 5,
    options: ['2', '3', '5', '9'],
    answerIndices: [0, 1, 2],
  ),
  MSQ(
    id: 'msq_9',
    bankId: '204',
    question: 'Which of the following are types of tissues in the human body?',
    variableIds: [],
    points: 5,
    options: ['Epithelial', 'Connective', 'Muscle', 'Nervous'],
    answerIndices: [0, 1, 2, 3],
  ),
  MSQ(
    id: 'msq_10',
    bankId: '205',
    question: 'Which of the following were causes of World War I?',
    variableIds: [],
    points: 6,
    options: [
      'Assassination of Archduke Franz Ferdinand',
      'Militarism',
      'Alliances',
      'Imperialism',
    ],
    answerIndices: [0, 1, 2, 3],
  ),
];