import '../../../models/questions/nat.dart';

final List<NAT> dummyNATs = [
  NAT(
    id: 'nat_1',
    bankId: '201',
    question: 'Calculate the acceleration (m/s²) of an object if force is 20 N and mass is 4 kg.',
    variableIds: [],
    points: 8,
    answer: 5.0,
  ),
  NAT(
    id: 'nat_2',
    bankId: '202',
    question: 'What is the value of π (up to 2 decimal places)?',
    variableIds: [],
    points: 5,
    answer: 3.14,
  ),
  NAT(
    id: 'nat_3',
    bankId: '203',
    question: 'What is the boiling point of water at sea level (in Celsius)?',
    variableIds: [],
    points: 3,
    answer: 100.0,
  ),
  NAT(
    id: 'nat_4',
    bankId: '204',
    question: 'Find the value of 7 × 8.',
    variableIds: [],
    points: 2,
    answer: 56.0,
  ),
  NAT(
    id: 'nat_5',
    bankId: '205',
    question: 'If the side of a square is 5 cm, calculate its area (in cm²).',
    variableIds: [],
    points: 4,
    answer: 25.0,
  ),
  NAT(
    id: 'nat_6',
    bankId: '201',
    question: 'What is the gravitational force (in N) between two 1 kg masses separated by 1 meter?',
    variableIds: [],
    points: 6,
    answer: 6.67e-11,
  ),
  NAT(
    id: 'nat_7',
    bankId: '202',
    question: 'Calculate the molar mass of CO₂ (in g/mol).',
    variableIds: [],
    points: 5,
    answer: 44.01,
  ),
  NAT(
    id: 'nat_8',
    bankId: '203',
    question: 'Solve for x: 2x + 3 = 7.',
    variableIds: [],
    points: 4,
    answer: 2.0,
  ),
  NAT(
    id: 'nat_9',
    bankId: '204',
    question: 'What is the pH of a solution with a hydrogen ion concentration of 1 x 10⁻⁷ M?',
    variableIds: [],
    points: 5,
    answer: 7.0,
  ),
  NAT(
    id: 'nat_10',
    bankId: '205',
    question: 'Calculate the density (in g/cm³) of an object with mass 50 g and volume 25 cm³.',
    variableIds: [],
    points: 4,
    answer: 2.0,
  ),
];