# Deployment and Service for production
# Uses production Docker image, references prod ConfigMap and Secret
# Includes resource requests/limits and health probes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  labels:
    app: backend
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      environment: prod
  template:
    metadata:
      labels:
        app: backend
        environment: prod
    spec:
      containers:
        - name: backend
          image: registry.example.com/backend:latest # Production image from registry
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config-prod
            - secretRef:
                name: backend-secret-prod
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-prod
  labels:
    app: backend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: backend
    environment: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
