// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8olHHNeUI3Vgc_Po2NoULX0tFwr6yvOY',
    appId: '1:287658179545:web:6fc8a5eea7ad7ecc87f7c8',
    messagingSenderId: '287658179545',
    projectId: 'lumenslate-30f66',
    authDomain: 'lumenslate-30f66.firebaseapp.com',
    storageBucket: 'lumenslate-30f66.firebasestorage.app',
    measurementId: 'G-ZRS4Z9T7GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gRS9XF6MmBfrXWyEfOkZhxDSJt4Zdeo',
    appId: '1:287658179545:android:b06e76e9ffb0ac0d87f7c8',
    messagingSenderId: '287658179545',
    projectId: 'lumenslate-30f66',
    storageBucket: 'lumenslate-30f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4-PNArXfcAqPbfJ5OstM5LcwrB3bl-s',
    appId: '1:287658179545:ios:f3d6da77805e464987f7c8',
    messagingSenderId: '287658179545',
    projectId: 'lumenslate-30f66',
    storageBucket: 'lumenslate-30f66.firebasestorage.app',
    androidClientId: '287658179545-chksfenutl0v9qmmf77suik3svl9nbgg.apps.googleusercontent.com',
    iosClientId: '287658179545-csmcsuto4jm0e35763rb6fua5mcvqa1j.apps.googleusercontent.com',
    iosBundleId: 'com.harentortoise.lumenslate',
  );

}