// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Fob3uXsc-EeUs6klXOR4Xlkc7IL7dGE',
    appId: '1:352355856094:web:1fe14860975a1247b99c4f',
    messagingSenderId: '352355856094',
    projectId: 'lumen-slate',
    authDomain: 'lumen-slate.firebaseapp.com',
    storageBucket: 'lumen-slate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMN_fS01BomWELCGNactGF9k5vgr087po',
    appId: '1:352355856094:android:010e419f1c95d942b99c4f',
    messagingSenderId: '352355856094',
    projectId: 'lumen-slate',
    storageBucket: 'lumen-slate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXAqdJcH7qrv_qu_FjjZ0H2tRfRJ9FGM',
    appId: '1:352355856094:ios:7ee3bf6d7ee94cd1b99c4f',
    messagingSenderId: '352355856094',
    projectId: 'lumen-slate',
    storageBucket: 'lumen-slate.firebasestorage.app',
    iosBundleId: 'com.harentortoise.lumenslate',
  );

}